### ISSUE TITLE
Transferring Vercel accounts

### ISSUE THREAD

**Issue by heidimok** [developmentseed/tecnico-energy-app#50]
## Context
We’ve hit a storage limit on our [Vercel](https://vercel.com/) account due to it being on the free hobby plan. 

## Action
We need to convert it to a paid plan to prevent being locked out of the database.

## Possible Steps Forward
1. Tecnico to sign up for a commercial, paid, Vercel account ($20 per user / month - I assume USD)
2. Update the application to use a DB hosted elsewhere, such as https://neon.tech/ (the same service that Vercel uses) or even a traditional AWS RDS instance

## Possible Workflows 
Once Tecnico has ownership over the Vercal account (or other account), we could either:
- Link it to the current Github Repo under Development Seed https://github.com/developmentseed/tecnico-energy-app 
- Tecnico could create their own repo so that the ownership is their, and create a fork of the Development Seed repo. Our team could then work off that repo.

**Comment by heidimok** [comment]
@alukach @Tammo-Feldmann @yellowcap Feel free to edit the details above as you know better than me! I just tried to lay out the situation.

@RicardoGomesIST Also welcome your thoughts on the better long-term approach for managing the data and github repo. The more immediate need is a paid plan as there will definitely only be more data added in the future. Daniel and our team could talk through more if needed to support.

**Comment by heidimok** [comment]
@RicardoGomesIST A quick note that Daniel Weissman is @yellowcap (we have two Daniels here at Development Seed). I know Daniel is at a conference so in case the timing doesn't work just a note that we can still wait until next week. Thank you!

**Comment by RicardoGomesIST** [comment]
Daniel Silva, desculpa (sorry)! Thank you Heidi
