### ISSUE TITLE
Need application Title and Description.

### ISSUE THREAD

**Issue by alukach** [developmentseed/tecnico-energy-app#65]
The application needs a Title and Description.  The Title (currently set to `Técnico`) is visible on your browser's navigation bar and the Description (currently set to `An interactive application to help others understand the energy consumption of urban environments.`) is visible when a link is unfurled (previewed) in chat applications and in web search results.

**Comment by RicardoGomesIST** [comment]
Hi Anthony. 

How definitive is the title? May we change it later? If so, it could be:

“IN+ Urban Dashboard” 

If not, I must check with the rest of the team

You can keep the description if it follows the same logic

Thank you 

 �

 �

From: Anthony Lukach ***@***.***> 
Sent: Friday, May 17, 2024 6:21 PM
To: developmentseed/tecnico-energy-app ***@***.***>
Cc: RicardoGomesIST ***@***.***>; Assign ***@***.***>
Subject: [developmentseed/tecnico-energy-app] Need application Title and Description. (Issue #65)

 �

The application needs a Title and Description. The Title (currently set to Técnico) is visible on your browser's navigation bar and the Description (currently set to An interactive application to help others understand the energy consumption of urban environments.) is visible when a link is unfurled (previewed) in chat applications and in web search results.

**Comment by alukach** [comment]
It can absolutely be changed later. It is set in `app/layout.tsx`:

https://github.com/developmentseed/tecnico-energy-app/blob/680d8ebb6a9e8f34408ccd686c0b523a5c11c444/app/layout.tsx#L4-L8

I've updated the title just now in commit [680d8eb](https://github.com/developmentseed/tecnico-energy-app/commit/680d8ebb6a9e8f34408ccd686c0b523a5c11c444).
